### ISSUE TITLE
Backup failed: requested plugin is not available: pgbackrest.cnpg.opera.com

### ISSUE THREAD

**Issue by bbigras** [operasoftware/cnpg-plugin-pgbackrest#18]
```sh
❯ kubectl get pods -n cnpg-system
NAME                                  READY   STATUS    RESTARTS   AGE
cnpg-cloudnative-pg-948c96955-st92v   1/1     Running   0          4h59m
pgbackrest-7cbf74c6c7-n49cb           1/1     Running   0          50m
❯ kubectl get pods -n keycloak
NAME                   READY   STATUS    RESTARTS   AGE
keycloak-0             1/1     Running   0          7h48m
postgresql-cluster-1   1/1     Running   0          4h56m
❯ kubectl get archive -n keycloak
NAME        AGE
backblaze   11m
❯ kubectl get backup -n keycloak
NAME                        AGE   CLUSTER              METHOD   PHASE    ERROR
backup-postgresql-cluster   3m    postgresql-cluster   plugin   failed   requested plugin is not available: pgbackrest.cnpg.opera.com
```

Note that my deployment doesn't match the one from your instructions.

```sh
❯ kubectl get deployment -n cnpg-system cnpg-controller-manager
Error from server (NotFound): deployments.apps "cnpg-controller-manager" not found
❯ kubectl get deployment -n cnpg-system
NAME                  READY   UP-TO-DATE   AVAILABLE   AGE
cnpg-cloudnative-pg   1/1     1            1           44d
pgbackrest            1/1     1            1           52m
```

I'm using
```yaml
helmCharts:
  - name: cloudnative-pg
    version: 0.24.0
    repo: https://cloudnative-pg.github.io/charts
    releaseName: cnpg
    namespace: cnpg-system
```
